# Generated by Django 3.0.3 on 2020-03-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
