# Generated by Django 3.0.3 on 2020-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
