# Generated by Django 3.0.3 on 2020-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlogin_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(default='0001', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
