# Generated by Django 3.0.3 on 2020-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200322_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='confirm_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.AutoField(auto_created=True, default='0001', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
