# Generated by Django 3.0.3 on 2020-03-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('gross_sale', models.FloatField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.FloatField(max_length=50)),
            ],
        ),
    ]
